In [1]:
import torch
print(torch.cuda.is_available())  # Trả về True nếu có GPU hỗ trợ CUDA
print(torch.cuda.device_count())  # Số lượng GPU có thể sử dụng
print(torch.cuda.get_device_name(0))  # Tên GPU đầu tiên (nếu có)

True
1
Quadro T2000 with Max-Q Design


In [ ]:
!pip install scikit-learn


In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [3]:
true_b = 1 
true_w = 2
N = 100

# generate data
np.random.seed(42)

x = np.random.rand(N, 1)

epsilon = (.1* np.random.randn(N, 1))
y = true_b + true_w * x + epsilon

In [4]:
x

array([[0.37454012],
       [0.95071431],
       [0.73199394],
       [0.59865848],
       [0.15601864],
       [0.15599452],
       [0.05808361],
       [0.86617615],
       [0.60111501],
       [0.70807258],
       [0.02058449],
       [0.96990985],
       [0.83244264],
       [0.21233911],
       [0.18182497],
       [0.18340451],
       [0.30424224],
       [0.52475643],
       [0.43194502],
       [0.29122914],
       [0.61185289],
       [0.13949386],
       [0.29214465],
       [0.36636184],
       [0.45606998],
       [0.78517596],
       [0.19967378],
       [0.51423444],
       [0.59241457],
       [0.04645041],
       [0.60754485],
       [0.17052412],
       [0.06505159],
       [0.94888554],
       [0.96563203],
       [0.80839735],
       [0.30461377],
       [0.09767211],
       [0.68423303],
       [0.44015249],
       [0.12203823],
       [0.49517691],
       [0.03438852],
       [0.9093204 ],
       [0.25877998],
       [0.66252228],
       [0.31171108],
       [0.520

In [5]:
# Shuffles the indices
idx = np.arange(N)
np.random.shuffle(idx)

# Uses first 80 random indices for train
train_idx = idx[:int(N*.8)]
# Uses the remaining indices for validation
val_idx = idx[int(N*.8):]

# Generates train and validation sets
x_train, y_train = x[train_idx], y[train_idx]
x_val, y_val = x[val_idx], y[val_idx]

In [7]:
print(x_train, y_train) 

[[0.77127035]
 [0.06355835]
 [0.86310343]
 [0.02541913]
 [0.73199394]
 [0.07404465]
 [0.19871568]
 [0.31098232]
 [0.47221493]
 [0.96958463]
 [0.12203823]
 [0.77513282]
 [0.80219698]
 [0.72960618]
 [0.09767211]
 [0.18485446]
 [0.15601864]
 [0.02058449]
 [0.98688694]
 [0.62329813]
 [0.70807258]
 [0.59789998]
 [0.92187424]
 [0.63755747]
 [0.28093451]
 [0.25877998]
 [0.11959425]
 [0.72900717]
 [0.94888554]
 [0.60754485]
 [0.5612772 ]
 [0.4937956 ]
 [0.18182497]
 [0.27134903]
 [0.96990985]
 [0.21233911]
 [0.18340451]
 [0.86617615]
 [0.37454012]
 [0.29122914]
 [0.80839735]
 [0.05808361]
 [0.83244264]
 [0.54269608]
 [0.77224477]
 [0.88721274]
 [0.0884925 ]
 [0.04522729]
 [0.59241457]
 [0.68423303]
 [0.71324479]
 [0.03438852]
 [0.60111501]
 [0.81546143]
 [0.44015249]
 [0.32518332]
 [0.78517596]
 [0.76078505]
 [0.49517691]
 [0.19967378]
 [0.95071431]
 [0.29214465]
 [0.13949386]
 [0.31171108]
 [0.70685734]
 [0.11586906]
 [0.35846573]
 [0.00552212]
 [0.19598286]
 [0.89482735]
 [0.45606998]
 [0.52

In [8]:
np.random.seed(42)
b = np.random.randn(1)
w = np.random.randn(1)

print(b, w)

[0.49671415] [-0.1382643]


In [11]:
 yhat = b + w * x_train

In [12]:
# Bước 2 - Tính toán hàm mất mát
error = (yhat - y_train)

# MSE - Trung bình bình phương sai số
loss = (error ** 2).mean()

print(loss)

2.7421577700550976


In [13]:
# Giá trị tham số thực sự
# true_b = 1
# true_w = 2

# Chia khoảng [-3, +3] thành 101 điểm đều nhau
b_range = np.linspace(true_b - 3, true_b + 3, 101)
w_range = np.linspace(true_w - 3, true_w + 3, 101)

# Tạo lưới giá trị cho tất cả cặp (b, w)
bs, ws = np.meshgrid(b_range, w_range)

print(bs.shape, ws.shape)


(101, 101) (101, 101)


In [14]:
bs


array([[-2.  , -1.94, -1.88, ...,  3.88,  3.94,  4.  ],
       [-2.  , -1.94, -1.88, ...,  3.88,  3.94,  4.  ],
       [-2.  , -1.94, -1.88, ...,  3.88,  3.94,  4.  ],
       ...,
       [-2.  , -1.94, -1.88, ...,  3.88,  3.94,  4.  ],
       [-2.  , -1.94, -1.88, ...,  3.88,  3.94,  4.  ],
       [-2.  , -1.94, -1.88, ...,  3.88,  3.94,  4.  ]])

In [15]:
dummy_x = x_train[0]
dummy_yhat = bs + ws * dummy_x
dummy_yhat.shape


(101, 101)

In [16]:
all_predictions = np.apply_along_axis(
  func1d=lambda x: bs + ws * x,
  axis=1,
  arr=x_train,
)
all_predictions.shape

(80, 101, 101)

In [17]:
all_labels = y_train.reshape(-1, 1, 1)
all_labels.shape


(80, 1, 1)

In [18]:
all_errors = (all_predictions - all_labels)
all_errors.shape

(80, 101, 101)

In [19]:
all_losses = (all_errors ** 2).mean(axis=0)
all_losses.shape


(101, 101)

In [20]:
b_grad = 2*error.mean()
w_grad = 2*(x_train * error).mean()
print(b_grad, w_grad)

-3.044811379650508 -1.8337537171510832
